//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FabriqueUnite : IFabriqueUnite
{
	public static List<IUnite> CreerUnites(TypePeuple type, int nbUnites, int joueur) {

        List<IUnite> res = new List<IUnite>();
        switch (type) {
            case TypePeuple.GAULOIS:
                for (int i = 0; i < nbUnites; i++) {
                    res.Add(new UniteGaulois(joueur));
                }
                break;
            case TypePeuple.NAINS:
                for (int i = 0; i < nbUnites; i++)
                {
                    res.Add(new UniteNain(joueur));
                }
                break;
            case TypePeuple.VIKING:
                for (int i = 0; i < nbUnites; i++)
                {
                    res.Add(new UniteViking(joueur));
                }
                break;
            default:
                throw new Exception("Peuple non existant");
        }
        return res;
	}

}

