//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class UniteNain : Unite
{
    public UniteNain(int j)
    {
    }
	public override void nouveauTour(TypeCase caseActuelle)
	{
		throw new System.NotImplementedException();
	}

}

