//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Carte : ICarte
{
	protected virtual List<Case> _cases
	{
		get;
		set;
	}

	protected virtual Partie _partie
	{
		get;
		set;
	}

	protected virtual IFabriqueCase _fabrique
	{
		get;
		set;
	}

	protected virtual List<TypeCase> _grilleCases
	{
		get;
		set;
	}

	public virtual List<TypeCase> getGrille()
	{
		throw new System.NotImplementedException();
	}

	public virtual Case getCase(Coordonnee c)
	{
		throw new System.NotImplementedException();
	}

	public abstract List<Coordonnee> getEmplacementUnites(int nbJoueurs);

	public abstract List<Direction> getDirectionsAutorisees(Coordonnee c);

}

