//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CarteDemo : Carte
{
	public override Vector<Coordonnee> getEmplacementUnites(int nbJoueurs)
	{
		throw new System.NotImplementedException();
	}

	public override Vector<Direction> getDirectionsAutorisees(Coordonnee c)
	{
		throw new System.NotImplementedException();
	}

}

