//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Coordonnee
{
	private int _x
	{
		get;
		set;
	}

	private int _y
	{
		get;
		set;
	}

	private static int _hauteurCarte
	{
		get;
		set;
	}

	private static int _largeurCarte
	{
		get;
		set;
	}

	public static Coordonnee enCoordonnee(int n)
	{
		throw new System.NotImplementedException();
	}

	public static Coordonnee enCoordonnee(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool equal(Coordonne c)
	{
		throw new System.NotImplementedException();
	}

	public virtual int getX()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getY()
	{
		throw new System.NotImplementedException();
	}

}

