//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FabriqueCase : IFabriqueCase
{
	public virtual List<Case> creerCases(int nbCases, TypeCase t)
	{
		throw new System.NotImplementedException();
	}

}

