//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FabriqueUnite : IFabriqueUnite
{
	public virtual Vector<IUnite> creerUnites(TypePeuple type, int nbUnites, int joueur)
	{
		throw new System.NotImplementedException();
	}

}

