//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface ICarte 
{
	Vector<TypeCase> getGrille();

	Case getCase(Coordonnee c);

	Vector<Coordonnee> getEmplacementUnites(int nbJoueurs);

	Vector<Direction> getDirectionsAutorisees(Coordonnee c);

}

