//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IMonteurPartie 
{
	IPartie creerPartie(File p);

	IPartie creerPartie(TypeCarte tc, Vector<TypePeuple> tp, string nomPartie);

}

