//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IPeuple 
{
	Vector<IUnite> getUnites();

	int getNombreUnites();

	void tuerUnite(IUnite unite);

	void creerUnite(int nb, int idJoueur);

}

