//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IStrategiePartie 
{
	IPartie creerPartie(string nomPartie, List<TypePeuple> tp);

	IPartie creerPartie(string nomPartie, List<TypePeuple> tp, List<List<Coordonnee>> unites, List<TypeCase> grille);

}

