//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IUnite 
{
	void deplacer(Coordonnee caseCible, TypeCase caseActuelle);

	boolean attaquer(IUnite uniteCible);

	int getCoordonnees();

	int getAttaque();

	int getDefense();

	void nouveauTour(TypeCase caseActuelle);

	int getValeur();

	int getPointsDeVie();

	int getPointDeplacement();

}

