//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Joueur : IJoueur
{
	private int _id
	{
		get;
		set;
	}

	private static int NOMBREJOUEUR
	{
		get;
		set;
	}

	private IPeuple _peuple
	{
		get;
		set;
	}

	private bool _enJeu
	{
		get;
		set;
	}

	public virtual int getId()
	{
		throw new System.NotImplementedException();
	}

	public virtual IPeuple getPeuple()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool enJeu()
	{
		throw new System.NotImplementedException();
	}

}

