//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class StrategiePartie : IStrategiePartie
{
	protected virtual List<TypeCase> genererGrilleAleatoire(int hauteur, int largeur)
	{
		throw new System.NotImplementedException();
	}

	public abstract IPartie creerPartie(string tc, List<TypePeuple> tp);

	protected abstract ICarte monterCarte();

	protected abstract ICarte monterCarte(List<TypeCase> grille);

	public abstract IPartie creerPartie(string tp, List<TypePeuple> unites, List<List<Coordonnee>> grille, List<TypeCase> grille);

}

