//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Unite : IUnite
{
	protected virtual int _attaque
	{
		get;
		set;
	}

	protected virtual int _defense
	{
		get;
		set;
	}

	protected virtual int _pointsDeVie
	{
		get;
		set;
	}

	protected virtual int _pointsDeplacement
	{
		get;
		set;
	}

	protected virtual Coordonnee _coordonnee
	{
		get;
		set;
	}

	protected virtual int _valeur
	{
		get;
		set;
	}

	protected virtual int _joueur
	{
		get;
		set;
	}

	public virtual void deplacer(Coordonnee caseCible, TypeCase caseActuelle)
	{
		throw new System.NotImplementedException();
	}

	public virtual boolean attaquer(IUnite uniteCible)
	{
		throw new System.NotImplementedException();
	}

	public virtual int getAttaque()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getCoordonnees()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getDefense()
	{
		throw new System.NotImplementedException();
	}

	public abstract void nouveauTour(TypeCase caseActuelle);

	public virtual int getValeur()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getPointsDeVie()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getIdJoueur()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getPointDeplacement()
	{
		throw new System.NotImplementedException();
	}

}

