//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FabriqueCase : IFabriqueCase
{
    public static Dictionary<TypeCase, Case> InitialiserCases()
	{
        Dictionary<TypeCase, Case> res = new Dictionary<TypeCase, Case>();
        res.Add(TypeCase.DESERT, new CaseDesert());
        res.Add(TypeCase.EAU, new CaseEau());
        res.Add(TypeCase.FORET, new CaseForet());
        res.Add(TypeCase.MONTAGNE, new CaseMontagne());
        res.Add(TypeCase.PLAINE, new CasePlaine());
        return res;
	}

    public static TypeCase[][] CreerGrille(int nbCases)
    {
        /* TODO : lien avec le wrapper */
        throw new System.NotImplementedException();
    }
}

