//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Joueur : IJoueur
{
	private int _id;
	private static int NOMBREJOUEUR = 0;
	private IPeuple _peuple;
    private int _points;

    public Joueur(TypePeuple t) {
        _id = ++NOMBREJOUEUR;
        _peuple = new Peuple(t);
        _points = 0;
    }

	public int GetId() {
        return _id;
	}

	public IPeuple GetPeuple() {
		return _peuple;
	}

	public bool EnJeu()	{
        return _peuple.GetNombreUnites() > 0;
	}

    public void NouveauTour() {
        _peuple.NouveauTour();
        /* TODO Calcul des points*/
    }
}

