//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MonteurPetit : StrategiePartie
{
	protected override ICarte monterCarte()
	{
		throw new System.NotImplementedException();
	}

	protected override ICarte monterCarte(TypeCase[][] grille)
	{
		throw new System.NotImplementedException();
	}

	public override IPartie creerPartie(string tc, List<TypePeuple> tp)
	{
		throw new System.NotImplementedException();
	}

	public override IPartie creerPartie(string tp, List<TypePeuple> unites, Vector<Vector<Coordonnee>> grille, Vector<TypeCase> grille)
	{
		throw new System.NotImplementedException();
	}

}

